# Generated by Django 6.0.2 on 2026-03-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['updated_at']},
        ),
    ]
