# Generated by Django 6.0.2 on 2026-03-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderstatushistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('bank_transfer', 'Bank Transfer'), ('zelle_payment', 'Zelle Payment')], max_length=150),
        ),
    ]
