# Generated by Django 6.0.2 on 2026-03-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='representative_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
