# Generated by Django 6.0.2 on 2026-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_representative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='representative_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
