# Generated by Django 6.0.2 on 2026-04-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_representative_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
