# Generated by Django 6.0.2 on 2026-03-01 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('dosage_strength', models.IntegerField(help_text='The numeric value (e.g., 10, 50, 1500)')),
                ('dosage_unit', models.CharField(default='mg', help_text='The unit of measurement (e.g., mg, mcg)', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
