# Generated by Django 6.0.2 on 2026-03-15 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_information_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description_content', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_descriptions', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
