# Generated by Django 6.0.2 on 2026-03-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_additionaldescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldescription',
            name='description_title',
        ),
    ]
