# Generated by Django 6.0.2 on 2026-03-28 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_additionaldescription_description_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information_pdf',
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='product_pdfs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
