# Generated by Django 6.0.2 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='liability_waiver_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
