# Generated by Django 6.0.2 on 2026-03-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_liability_waiver_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
