# Generated by Django 6.0.2 on 2026-03-17 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_quantity_cartitem_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.25'), max_digits=5),
        ),
    ]
