# Generated by Django 6.0.2 on 2026-04-28 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Consultation type name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Consultation type description', null=True)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Consultation type fee', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Consultation type availability')),
                ('is_recommended', models.BooleanField(default=False, help_text='Consultation type recommendation')),
                ('facility_1', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_2', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_3', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_4', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_5', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_6', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Consultation Type',
                'verbose_name_plural': 'Consultation Types',
                'ordering': ['-created_at'],
            },
        ),
    ]
