# Generated by Django 6.0.2 on 2026-04-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lab_recommended',
            field=models.BooleanField(default=False, help_text='Lab recommended'),
        ),
    ]
