# Generated by Django 6.0.3 on 2026-04-27 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Doctor name', max_length=255)),
                ('is_available', models.BooleanField(default=True, help_text='Doctor availability')),
                ('services', models.ManyToManyField(help_text='Services associated with this doctor', related_name='doctors', to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
