# Generated by Django 6.0.2 on 2026-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='resend_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
