# Generated by Django 6.0.2 on 2026-05-04 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_appointmentstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_goals', models.JSONField(blank=True, default=list, help_text='List of selected health goals')),
                ('exercise_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('used_peptides_before', models.BooleanField(default=False)),
                ('previous_peptides_details', models.TextField(blank=True, help_text='Required if used_peptides_before is True', null=True)),
                ('peptides_used', models.JSONField(blank=True, default=list)),
                ('safety_screening', models.JSONField(blank=True, default=list)),
                ('relevant_medical_history', models.JSONField(blank=True, default=list)),
                ('treatment_goals_text', models.TextField(blank=True, null=True)),
                ('desired_timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('agreed_to_telehealth', models.BooleanField(default=False)),
                ('agreed_to_privacy_policy', models.BooleanField(default=False)),
                ('agreed_to_hipaa', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_data', to='appointment.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
