# Generated by Django 6.0.2 on 2026-02-25 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('representative_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representatives',
                'db_table': 'representatives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['representative_code'], name='representat_represe_cd71ab_idx'), models.Index(fields=['company'], name='representat_company_458dc4_idx'), models.Index(fields=['is_active', '-created_at'], name='representat_is_acti_b9f331_idx')],
            },
        ),
    ]
