# Generated by Django 6.0.2 on 2026-03-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='representatives/avatars/'),
        ),
    ]
